export type ApiCoverageLevel =
  | 'positive-crud'
  | 'positive-business'
  | 'contract-only'
  | 'deferred-external'
  | 'blocked-missing-data';

export type ApiEndpointStatus = 'covered' | 'planned' | 'blocked';

export const ALLOWED_API_GROUPS = [
  '菜单管理',
  '菜单全局搜索',
  '菜单组管理',
  '订单管理',
  '订单支付',
  '分类管理',
  '角色管理',
  '商品管理',
  '税费管理',
  '折扣管理',
  'global-option-category-controller',
  'global-option-controller',
  'SPU 库存管理',
] as const;

export const API_SPEC_FILES = {
  menuCatalog: 'tests/api/business/menu-catalog.api.spec.ts',
  saleItem: 'tests/api/business/sale-item.api.spec.ts',
  orderPayment: 'tests/api/business/order-payment.api.spec.ts',
  adminConfig: 'tests/api/business/admin-config.api.spec.ts',
  contractSmoke: 'tests/api/contracts/contract-smoke.api.spec.ts',
  endpointTax: 'tests/api/endpoints/admin-config/tax.endpoint.api.spec.ts',
  endpointDiscount: 'tests/api/endpoints/admin-config/discount.endpoint.api.spec.ts',
  endpointRole: 'tests/api/endpoints/admin-config/role.endpoint.api.spec.ts',
  endpointMenu: 'tests/api/endpoints/menu/menu.endpoint.api.spec.ts',
  endpointMenuGroup: 'tests/api/endpoints/menu/menu-group.endpoint.api.spec.ts',
  endpointCategory: 'tests/api/endpoints/menu/category.endpoint.api.spec.ts',
  endpointSaleItem: 'tests/api/endpoints/sale-item/sale-item.endpoint.api.spec.ts',
  endpointSpu: 'tests/api/endpoints/sale-item/spu.endpoint.api.spec.ts',
  endpointOrder: 'tests/api/endpoints/order/order.endpoint.api.spec.ts',
  endpointPayment: 'tests/api/endpoints/order/payment.endpoint.api.spec.ts',
} as const;

export type ApiBatchGroup = (typeof ALLOWED_API_GROUPS)[number];
export type ApiSpecFile = (typeof API_SPEC_FILES)[keyof typeof API_SPEC_FILES];

export type ApiCaseCoverage = {
  positive: boolean;
  negative: boolean;
  boundary: boolean;
  knownIssue?: string;
};

export type FirstBatchApiCase = {
  method: 'GET' | 'POST' | 'PUT' | 'DELETE';
  path: string;
  group: ApiBatchGroup;
  coverage: ApiCoverageLevel;
  specFile: ApiSpecFile;
  endpointStatus: ApiEndpointStatus;
  endpointSpecFile?: ApiSpecFile;
  caseCoverage: ApiCaseCoverage;
  riskNote: string;
};

type FirstBatchApiCaseInput = Omit<FirstBatchApiCase, 'caseCoverage'>;

const NEGATIVE_CASE_KEYS = new Set<string>([
  'POST /api/menu/menu',
  'PUT /api/menu/menu',
  'GET /api/menu/menu/{id}',
  'POST /api/menu/menuGroup',
  'PUT /api/menu/menuGroup',
  'GET /api/menu/menuGroup/{id}',
  'POST /api/order/save',
  'GET /api/order/fetch',
  'POST /api/order/void',
  'POST /api/payment/record/delete',
  'POST /api/payment/record/save',
  'POST /api/menu/menuCategory',
  'PUT /api/menu/menuCategory',
  'GET /api/menu/menuCategory/{id}',
  'POST /api/admin/role/delete',
  'POST /api/admin/role/save',
  'POST /api/menu/menuSaleItem',
  'PUT /api/menu/menuSaleItem',
  'GET /api/menu/menuSaleItem/{id}',
  'POST /api/tax/delete',
  'POST /api/tax/save',
  'POST /api/discount/delete',
  'POST /api/spu/menuSaleItem/assign',
  'POST /api/spu/stockOperation',
]);

const BOUNDARY_CASE_KEYS = new Set<string>([
  'GET /api/menu/menus',
  'GET /api/order/list',
  'GET /api/tax/list',
  'GET /api/discount/list',
  'GET /api/admin/role/list',
  'GET /api/menu/menuSaleItems/search',
]);

const KNOWN_ISSUES_BY_KEY = new Map<string, string>([
  ['POST /api/discount/save', '空对象会返回 code=0 并创建折扣，暂不放入普通异常回归。'],
  ['DELETE /api/menu/menuSaleItem/{id}', '删除不存在商品会返回 code=0 success，暂不放入普通异常回归。'],
]);

const firstBatchApiCaseInputs: FirstBatchApiCaseInput[] = [
  {
    method: 'GET',
    path: '/api/menu/checkMenuLastUpdateTime',
    group: '菜单管理',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '缓存时间戳校验接口，先覆盖响应契约，避免依赖真实菜单缓存刷新时机。',
  },
  {
    method: 'POST',
    path: '/api/menu/clearCache',
    group: '菜单管理',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '清理缓存会影响全局菜单状态，先做契约覆盖，不纳入正向数据变更链路。',
  },
  {
    method: 'GET',
    path: '/api/menu/fetchGlobalOption',
    group: '菜单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '读取全局选项属于菜单配置核心查询，需要覆盖可用样例数据。',
  },
  {
    method: 'GET',
    path: '/api/menu/listGlobalOption',
    group: '菜单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '全局选项列表影响点餐加料展示，需要验证列表结构稳定。',
  },
  {
    method: 'GET',
    path: '/api/menu/liteMenu/{id}',
    group: '菜单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '轻量菜单读取依赖现有菜单样例，覆盖核心展示字段。',
  },
  {
    method: 'GET',
    path: '/api/menu/menu',
    group: '菜单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '当前菜单读取是后续菜单链路前置条件，需要正向覆盖。',
  },
  {
    method: 'POST',
    path: '/api/menu/menu',
    group: '菜单管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointMenu,
    riskNote: '菜单创建是核心 CRUD，需要使用隔离测试数据验证。',
  },
  {
    method: 'PUT',
    path: '/api/menu/menu',
    group: '菜单管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointMenu,
    riskNote: '菜单更新是核心 CRUD，需要验证更新后字段回读。',
  },
  {
    method: 'GET',
    path: '/api/menu/menu/{id}',
    group: '菜单管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointMenu,
    riskNote: '菜单详情读取用于 CRUD 回读校验，需要稳定样例菜单。',
  },
  {
    method: 'GET',
    path: '/api/menu/menus',
    group: '菜单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointMenu,
    riskNote: '菜单列表是配置入口，覆盖基本列表结构和分页返回。',
  },
  {
    method: 'GET',
    path: '/api/search/menu',
    group: '菜单全局搜索',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointMenu,
    riskNote: '全局搜索依赖菜单索引数据，优先覆盖可搜索样例和响应结构。',
  },
  {
    method: 'GET',
    path: '/api/menu/group/list',
    group: '菜单组管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointMenuGroup,
    riskNote: '菜单组列表是菜单配置导航入口，需要覆盖查询契约。',
  },
  {
    method: 'GET',
    path: '/api/menu/group/listGroupCategoryItems',
    group: '菜单组管理',
    coverage: 'blocked-missing-data',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: 'Swagger 标注未实现；当前返回 501，需要后端实现或现场可用模块后再升级覆盖。',
  },
  {
    method: 'GET',
    path: '/api/menu/group/saleItem/all',
    group: '菜单组管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '菜单组商品全集用于配置选择，需要验证基础列表可用。',
  },
  {
    method: 'POST',
    path: '/api/menu/menuGroup',
    group: '菜单组管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointMenuGroup,
    riskNote: '菜单组创建是核心 CRUD，需要隔离数据覆盖。',
  },
  {
    method: 'PUT',
    path: '/api/menu/menuGroup',
    group: '菜单组管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointMenuGroup,
    riskNote: '菜单组更新是核心 CRUD，需要校验更新后回读。',
  },
  {
    method: 'POST',
    path: '/api/menu/menuGroup/batch/copy',
    group: '菜单组管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '按现场抓包确认请求体为 menuId 和 groupIds，使用运行时创建的菜单组 ID 覆盖真实复制链路。',
  },
  {
    method: 'DELETE',
    path: '/api/menu/menuGroup/batch/delete',
    group: '菜单组管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '按现场抓包确认请求体为 groupIds，使用运行时创建的菜单组 ID 覆盖真实批量删除链路。',
  },
  {
    method: 'PUT',
    path: '/api/menu/menuGroup/batch/sequence',
    group: '菜单组管理',
    coverage: 'blocked-missing-data',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '空 payload 会触发后端 500；需要使用现场抓包或运行时创建的菜单组顺序数据后再升级覆盖。',
  },
  {
    method: 'PUT',
    path: '/api/menu/menuGroup/batch/update',
    group: '菜单组管理',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '批量更新影响范围大，先用契约烟测保护接口形态。',
  },
  {
    method: 'DELETE',
    path: '/api/menu/menuGroup/{id}',
    group: '菜单组管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointMenuGroup,
    riskNote: '单个菜单组删除属于 CRUD 闭环，需要使用测试创建的数据。',
  },
  {
    method: 'GET',
    path: '/api/menu/menuGroup/{id}',
    group: '菜单组管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointMenuGroup,
    riskNote: '菜单组详情用于 CRUD 回读，需要覆盖存在记录。',
  },
  {
    method: 'GET',
    path: '/api/menu/menuGroups',
    group: '菜单组管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '菜单组分页列表影响配置管理入口，需要正向覆盖。',
  },
  {
    method: 'GET',
    path: '/api/order/checkOrderExistsByPhoneAndMember',
    group: '订单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.orderPayment,
    endpointStatus: 'planned',
    riskNote: '订单存在性查询依赖会员和手机号样例，覆盖常规命中与未命中结构。',
  },
  {
    method: 'POST',
    path: '/api/order/clearTable',
    group: '订单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.orderPayment,
    endpointStatus: 'planned',
    riskNote: '清台会改变桌台订单状态，需要使用可控测试桌台数据。',
  },
  {
    method: 'POST',
    path: '/api/order/combine',
    group: '订单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.orderPayment,
    endpointStatus: 'planned',
    riskNote: '合单涉及多订单状态变化，需要覆盖受控正向业务路径。',
  },
  {
    method: 'POST',
    path: '/api/order/dailyClose',
    group: '订单管理',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '日结影响营业状态和报表，先覆盖契约，不在普通自动化中触发真实日结。',
  },
  {
    method: 'GET',
    path: '/api/order/detail/list',
    group: '订单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.orderPayment,
    endpointStatus: 'planned',
    riskNote: '订单明细列表是订单校验基础，需要覆盖可用订单样例。',
  },
  {
    method: 'GET',
    path: '/api/order/fetch',
    group: '订单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.orderPayment,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointOrder,
    riskNote: '订单详情读取是保存后校验入口，需要覆盖核心字段。',
  },
  {
    method: 'POST',
    path: '/api/order/item/move',
    group: '订单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.orderPayment,
    endpointStatus: 'planned',
    riskNote: '移动订单商品影响订单明细归属，需要受控订单数据覆盖。',
  },
  {
    method: 'GET',
    path: '/api/order/list',
    group: '订单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.orderPayment,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointOrder,
    riskNote: '订单列表是召回和查询入口，需要覆盖常规查询。',
  },
  {
    method: 'GET',
    path: '/api/order/listDeliveryTrack',
    group: '订单管理',
    coverage: 'blocked-missing-data',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '配送跟踪需要真实 deliveryId；无有效样例时后端下游会返回 ObjectId 转换错误，等待现场抓包补充。',
  },
  {
    method: 'POST',
    path: '/api/order/listOrdersByDateNumber',
    group: '订单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.orderPayment,
    endpointStatus: 'planned',
    riskNote: '按日期编号查单是业务查询路径，需要覆盖有数据和空结果结构。',
  },
  {
    method: 'POST',
    path: '/api/order/notice/send',
    group: '订单管理',
    coverage: 'deferred-external',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '发送通知可能依赖短信或外部通知通道，暂缓真实发送自动化。',
  },
  {
    method: 'GET',
    path: '/api/order/recall',
    group: '订单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.orderPayment,
    endpointStatus: 'planned',
    riskNote: '召回订单是前台核心业务入口，需要覆盖可召回订单列表。',
  },
  {
    method: 'POST',
    path: '/api/order/save',
    group: '订单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.orderPayment,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointOrder,
    riskNote: '保存订单是核心业务写入路径，需要覆盖正向下单数据。',
  },
  {
    method: 'POST',
    path: '/api/order/save/batch',
    group: '订单管理',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '批量保存订单会产生多笔业务数据，先覆盖契约并等待隔离数据方案。',
  },
  {
    method: 'POST',
    path: '/api/order/void',
    group: '订单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.orderPayment,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointOrder,
    riskNote: '作废订单是核心业务状态变更，需要使用测试订单覆盖。',
  },
  {
    method: 'POST',
    path: '/api/order/{id}/reopen',
    group: '订单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.orderPayment,
    endpointStatus: 'planned',
    riskNote: '重开订单依赖已关闭订单状态，需要受控数据覆盖。',
  },
  {
    method: 'POST',
    path: '/api/order/{id}/split',
    group: '订单管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.orderPayment,
    endpointStatus: 'planned',
    riskNote: '拆单会产生新订单关系，需要用隔离订单样例覆盖。',
  },
  {
    method: 'DELETE',
    path: '/api/payment/deletePaymentRecord',
    group: '订单支付',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.orderPayment,
    endpointStatus: 'planned',
    riskNote: '删除支付记录影响订单支付状态，需要使用测试支付记录覆盖。',
  },
  {
    method: 'POST',
    path: '/api/payment/record/delete',
    group: '订单支付',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.orderPayment,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointPayment,
    riskNote: '支付记录删除兼容接口，需要覆盖受控支付记录。',
  },
  {
    method: 'POST',
    path: '/api/payment/record/save',
    group: '订单支付',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.orderPayment,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointPayment,
    riskNote: '保存支付记录是本地支付链路核心写入，需要正向覆盖。',
  },
  {
    method: 'POST',
    path: '/api/payment/record/save/batch',
    group: '订单支付',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '批量保存支付记录涉及多笔状态变更，先覆盖契约。',
  },
  {
    method: 'POST',
    path: '/api/payment/refund',
    group: '订单支付',
    coverage: 'deferred-external',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '退款可能触达外部支付渠道，暂缓真实交易自动化。',
  },
  {
    method: 'POST',
    path: '/api/payment/savePaymentRecord',
    group: '订单支付',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.orderPayment,
    endpointStatus: 'planned',
    riskNote: '旧版保存支付记录接口仍在业务中使用，需要覆盖本地正向路径。',
  },
  {
    method: 'POST',
    path: '/api/payment/{id}/tip',
    group: '订单支付',
    coverage: 'deferred-external',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '小费调整通常绑定终端支付记录，暂缓真实外部支付覆盖。',
  },
  {
    method: 'POST',
    path: '/api/payment/{id}/void',
    group: '订单支付',
    coverage: 'deferred-external',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '支付撤销可能触达终端或支付渠道，暂缓真实外部调用。',
  },
  {
    method: 'DELETE',
    path: '/api/menu/abstractCategory/batch/delete',
    group: '分类管理',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '抽象分类批量删除破坏面较大，先覆盖契约。',
  },
  {
    method: 'GET',
    path: '/api/menu/abstractCategorys',
    group: '分类管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '抽象分类列表影响分类管理展示，需要覆盖基础查询。',
  },
  {
    method: 'GET',
    path: '/api/menu/abstractCategorys/search',
    group: '分类管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '抽象分类搜索依赖样例名称，需要覆盖搜索响应结构。',
  },
  {
    method: 'GET',
    path: '/api/menu/category/list',
    group: '分类管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '分类列表是商品配置入口，需要正向覆盖。',
  },
  {
    method: 'GET',
    path: '/api/menu/menu/{menuId}/menuCategories',
    group: '分类管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '按菜单读取分类用于菜单编辑，需要覆盖存在菜单样例。',
  },
  {
    method: 'POST',
    path: '/api/menu/menuCategory',
    group: '分类管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointCategory,
    riskNote: '菜单分类创建是核心 CRUD，需要隔离测试分类。',
  },
  {
    method: 'PUT',
    path: '/api/menu/menuCategory',
    group: '分类管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointCategory,
    riskNote: '菜单分类更新是核心 CRUD，需要校验更新后回读。',
  },
  {
    method: 'POST',
    path: '/api/menu/menuCategory/batch/copy',
    group: '分类管理',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '批量复制分类会生成多条配置数据，先覆盖契约。',
  },
  {
    method: 'PUT',
    path: '/api/menu/menuCategory/batch/update',
    group: '分类管理',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '批量更新分类影响展示配置，先做契约保护。',
  },
  {
    method: 'PUT',
    path: '/api/menu/menuCategory/quickEdit',
    group: '分类管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '分类快速编辑是常用配置写入，需要覆盖可控字段。',
  },
  {
    method: 'DELETE',
    path: '/api/menu/menuCategory/{id}',
    group: '分类管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointCategory,
    riskNote: '菜单分类删除是 CRUD 闭环，需要只删除测试创建数据。',
  },
  {
    method: 'GET',
    path: '/api/menu/menuCategory/{id}',
    group: '分类管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointCategory,
    riskNote: '菜单分类详情用于 CRUD 回读，需要覆盖存在记录。',
  },
  {
    method: 'GET',
    path: '/api/menu/menuCategorys/searchByName',
    group: '分类管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointCategory,
    riskNote: '按名称查分类依赖稳定样例名称，需要覆盖搜索契约。',
  },
  {
    method: 'POST',
    path: '/api/admin/role/delete',
    group: '角色管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.adminConfig,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointRole,
    riskNote: '角色删除属于权限配置 CRUD，需要限定测试角色。',
  },
  {
    method: 'GET',
    path: '/api/admin/role/list',
    group: '角色管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.adminConfig,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointRole,
    riskNote: '角色列表影响权限配置入口，需要覆盖基础查询。',
  },
  {
    method: 'POST',
    path: '/api/admin/role/save',
    group: '角色管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.adminConfig,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointRole,
    riskNote: '角色保存是权限配置核心 CRUD，需要使用隔离角色名称。',
  },
  {
    method: 'GET',
    path: '/api/menu/item/fetchItemOption',
    group: '商品管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'planned',
    riskNote: '商品选项读取影响点餐配置，需要覆盖存在商品样例。',
  },
  {
    method: 'GET',
    path: '/api/menu/item/fetchSaleItem',
    group: '商品管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointSaleItem,
    riskNote: '商品详情读取是商品链路核心查询，需要覆盖主要字段。',
  },
  {
    method: 'GET',
    path: '/api/menu/item/listByCategory',
    group: '商品管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'planned',
    riskNote: '按分类列商品是菜单展示核心路径，需要正向覆盖。',
  },
  {
    method: 'GET',
    path: '/api/menu/item/listComboSaleItem',
    group: '商品管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'planned',
    riskNote: '套餐商品列表影响组合商品配置，需要覆盖可用样例。',
  },
  {
    method: 'GET',
    path: '/api/menu/item/listItemOptions',
    group: '商品管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'planned',
    riskNote: '商品选项列表用于加料选择，需要验证列表结构。',
  },
  {
    method: 'GET',
    path: '/api/menu/item/listKTVItems',
    group: '商品管理',
    coverage: 'blocked-missing-data',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: 'KTV 商品依赖特定门店数据，当前缺少稳定样例，先记录缺口。',
  },
  {
    method: 'POST',
    path: '/api/menu/menuComponentItemAssoc',
    group: '商品管理',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '组件商品关联会影响套餐配置，先覆盖契约。',
  },
  {
    method: 'POST',
    path: '/api/menu/menuSaleItem',
    group: '商品管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointSaleItem,
    riskNote: '菜单商品创建是核心 CRUD，需要隔离测试商品。',
  },
  {
    method: 'PUT',
    path: '/api/menu/menuSaleItem',
    group: '商品管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointSaleItem,
    riskNote: '菜单商品更新是核心 CRUD，需要校验更新后回读。',
  },
  {
    method: 'POST',
    path: '/api/menu/menuSaleItem/batch/copy',
    group: '商品管理',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '批量复制商品会产生多条菜单商品，先覆盖契约。',
  },
  {
    method: 'POST',
    path: '/api/menu/menuSaleItem/batch/customizeMenuItemPriceAndMemberPrices',
    group: '商品管理',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '批量改价影响价格体系，先用契约烟测保护接口形态。',
  },
  {
    method: 'DELETE',
    path: '/api/menu/menuSaleItem/batch/delete',
    group: '商品管理',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '批量删除商品破坏面较大，先覆盖契约。',
  },
  {
    method: 'PUT',
    path: '/api/menu/menuSaleItem/batch/sequence',
    group: '商品管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'planned',
    riskNote: '按现场抓包确认请求体为 saleItemIds，使用运行时创建的商品 ID 覆盖真实批量排序链路。',
  },
  {
    method: 'PUT',
    path: '/api/menu/menuSaleItem/batch/update',
    group: '商品管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'planned',
    riskNote: '按现场抓包确认请求体为 saleItemIds 和批量字段，使用运行时创建的商品 ID 覆盖真实批量更新链路。',
  },
  {
    method: 'PUT',
    path: '/api/menu/menuSaleItem/batch/updateOutOfStock',
    group: '商品管理',
    coverage: 'blocked-missing-data',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '空 payload 会触发后端 500；需要现场抓包确认批量售罄请求体后再升级覆盖。',
  },
  {
    method: 'PUT',
    path: '/api/menu/menuSaleItem/link',
    group: '商品管理',
    coverage: 'blocked-missing-data',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '空 payload 会触发后端 500；需要真实 SPU 与菜单商品链接请求体后再升级覆盖。',
  },
  {
    method: 'PUT',
    path: '/api/menu/menuSaleItem/quickEdit',
    group: '商品管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'planned',
    riskNote: '商品快速编辑是常用配置写入，需要覆盖可控字段。',
  },
  {
    method: 'DELETE',
    path: '/api/menu/menuSaleItem/{id}',
    group: '商品管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointSaleItem,
    riskNote: '商品删除是 CRUD 闭环，需要只删除测试创建数据。',
  },
  {
    method: 'GET',
    path: '/api/menu/menuSaleItem/{id}',
    group: '商品管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointSaleItem,
    riskNote: '菜单商品详情用于 CRUD 回读，需要覆盖存在记录。',
  },
  {
    method: 'GET',
    path: '/api/menu/menuSaleItems/search',
    group: '商品管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointSaleItem,
    riskNote: '商品搜索是配置入口，需要覆盖稳定搜索条件。',
  },
  {
    method: 'GET',
    path: '/api/menu/menuSaleItems/searchByName',
    group: '商品管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointSaleItem,
    riskNote: '按名称查商品依赖样例商品名称，需要覆盖返回结构。',
  },
  {
    method: 'POST',
    path: '/api/tax/delete',
    group: '税费管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.adminConfig,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointTax,
    riskNote: '税费删除是配置 CRUD 闭环，需要限定测试税费。',
  },
  {
    method: 'GET',
    path: '/api/tax/list',
    group: '税费管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.adminConfig,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointTax,
    riskNote: '税费列表影响结账计算，需要覆盖基础查询。',
  },
  {
    method: 'POST',
    path: '/api/tax/save',
    group: '税费管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.adminConfig,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointTax,
    riskNote: '税费保存是配置 CRUD，需要使用隔离税费名称。',
  },
  {
    method: 'POST',
    path: '/api/discount/delete',
    group: '折扣管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.adminConfig,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointDiscount,
    riskNote: '折扣删除是配置 CRUD 闭环，需要限定测试折扣。',
  },
  {
    method: 'GET',
    path: '/api/discount/list',
    group: '折扣管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.adminConfig,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointDiscount,
    riskNote: '折扣列表影响下单优惠选择，需要覆盖基础查询。',
  },
  {
    method: 'POST',
    path: '/api/discount/save',
    group: '折扣管理',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.adminConfig,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointDiscount,
    riskNote: '折扣保存是配置 CRUD，需要使用隔离折扣名称。',
  },
  {
    method: 'POST',
    path: '/api/menu/globalOptionCategory',
    group: 'global-option-category-controller',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '全局选项分类创建是核心 CRUD，需要隔离测试分类。',
  },
  {
    method: 'PUT',
    path: '/api/menu/globalOptionCategory',
    group: 'global-option-category-controller',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '全局选项分类更新是核心 CRUD，需要校验回读。',
  },
  {
    method: 'DELETE',
    path: '/api/menu/globalOptionCategory/{id}',
    group: 'global-option-category-controller',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '全局选项分类删除是 CRUD 闭环，需要只删除测试数据。',
  },
  {
    method: 'GET',
    path: '/api/menu/globalOptionCategory/{id}',
    group: 'global-option-category-controller',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '全局选项分类详情用于 CRUD 回读，需要覆盖存在记录。',
  },
  {
    method: 'GET',
    path: '/api/menu/menu/{menuId}/globalOptionCategories',
    group: 'global-option-category-controller',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '按菜单读取全局选项分类用于菜单配置，需要覆盖存在菜单。',
  },
  {
    method: 'POST',
    path: '/api/menu/batchCustomizeGlobalOptionPriceAndMemberPrices',
    group: 'global-option-controller',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '批量改全局选项价格影响价格体系，先覆盖契约。',
  },
  {
    method: 'POST',
    path: '/api/menu/menuGlobalOption',
    group: 'global-option-controller',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '菜单全局选项创建是核心 CRUD，需要隔离测试选项。',
  },
  {
    method: 'PUT',
    path: '/api/menu/menuGlobalOption',
    group: 'global-option-controller',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '菜单全局选项更新是核心 CRUD，需要校验回读。',
  },
  {
    method: 'POST',
    path: '/api/menu/menuGlobalOption/batch/copy',
    group: 'global-option-controller',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '批量复制全局选项会产生多条配置数据，先覆盖契约。',
  },
  {
    method: 'DELETE',
    path: '/api/menu/menuGlobalOption/batch/delete',
    group: 'global-option-controller',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '批量删除全局选项破坏面较大，先覆盖契约。',
  },
  {
    method: 'PUT',
    path: '/api/menu/menuGlobalOption/batch/sequence',
    group: 'global-option-controller',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '批量排序全局选项影响展示顺序，先覆盖契约。',
  },
  {
    method: 'PUT',
    path: '/api/menu/menuGlobalOption/batch/update',
    group: 'global-option-controller',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '批量更新全局选项影响范围大，先覆盖契约。',
  },
  {
    method: 'DELETE',
    path: '/api/menu/menuGlobalOption/{id}',
    group: 'global-option-controller',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '菜单全局选项删除是 CRUD 闭环，需要只删除测试数据。',
  },
  {
    method: 'GET',
    path: '/api/menu/menuGlobalOption/{id}',
    group: 'global-option-controller',
    coverage: 'positive-crud',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '菜单全局选项详情用于 CRUD 回读，需要覆盖存在记录。',
  },
  {
    method: 'GET',
    path: '/api/menu/menuGlobalOptions/search',
    group: 'global-option-controller',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.menuCatalog,
    endpointStatus: 'planned',
    riskNote: '全局选项搜索是配置入口，需要覆盖稳定搜索条件。',
  },
  {
    method: 'POST',
    path: '/api/spu/hack/renumber',
    group: 'SPU 库存管理',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: 'SPU 重编号属于危险维护操作，先覆盖契约，不执行真实变更。',
  },
  {
    method: 'POST',
    path: '/api/spu/menuSaleItem/assign',
    group: 'SPU 库存管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointSpu,
    riskNote: 'SPU 分配菜单商品影响库存映射，需要使用隔离商品样例。',
  },
  {
    method: 'POST',
    path: '/api/spu/menuSaleItem/link',
    group: 'SPU 库存管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointSpu,
    riskNote: 'SPU 与菜单商品链接是库存业务关键路径，需要正向覆盖。',
  },
  {
    method: 'GET',
    path: '/api/spu/menuSaleItem/list/{code}',
    group: 'SPU 库存管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointSpu,
    riskNote: '按 SPU 编码读取菜单商品映射，需要覆盖稳定编码样例。',
  },
  {
    method: 'POST',
    path: '/api/spu/stockOperation',
    group: 'SPU 库存管理',
    coverage: 'positive-business',
    specFile: API_SPEC_FILES.saleItem,
    endpointStatus: 'covered',
    endpointSpecFile: API_SPEC_FILES.endpointSpu,
    riskNote: '单笔库存操作影响库存数量，需要使用隔离库存样例。',
  },
  {
    method: 'POST',
    path: '/api/spu/stockOperations',
    group: 'SPU 库存管理',
    coverage: 'contract-only',
    specFile: API_SPEC_FILES.contractSmoke,
    endpointStatus: 'blocked',
    riskNote: '批量库存操作影响多条库存记录，先覆盖契约。',
  },
];

export const firstBatchApiCases: FirstBatchApiCase[] = firstBatchApiCaseInputs.map(withCaseCoverage);

function withCaseCoverage(apiCase: FirstBatchApiCaseInput): FirstBatchApiCase {
  const key = toApiCaseKey(apiCase.method, apiCase.path);
  const knownIssue = KNOWN_ISSUES_BY_KEY.get(key);

  return {
    ...apiCase,
    caseCoverage: {
      positive: apiCase.coverage === 'positive-crud' || apiCase.coverage === 'positive-business',
      negative: NEGATIVE_CASE_KEYS.has(key),
      boundary: BOUNDARY_CASE_KEYS.has(key),
      ...(knownIssue === undefined ? {} : { knownIssue }),
    },
  };
}

function toApiCaseKey(method: FirstBatchApiCaseInput['method'], path: string): string {
  return `${method} ${path}`;
}
